---
title: "Add biomass information to dataset"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Load packages to be used in the analysis

```{r}

ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

packages <- c("tidyverse", "readxl", "RODBC", "here", "rnaturalearth", "rnaturalearthdata", "maps", "mapdata", "marmap", "rgdal")

ipak(packages)

```




Biomass, production conversions

```{r}

#First read in the zooplankton data set

NBS_Process_Final <- read.csv(here("Processed-Data", "NBS_Zoop_Process_Final.csv"))

#NOw read in the biomass conversion data set

Biomass_annotated <- read_xlsx(here("Biomass", "Biomass-Annotated.xlsx"))

#Merge the two data sets based on TAXA_COARSE, STAGE_NAME, SEX_NAME

NBS_Process_Final <- left_join(NBS_Process_Final, Biomass_annotated, by = c("TAXA_COARSE", "STAGE_NAME", "SEX_NAME"))

#Do some tidying to eliminate some columns

NBS_Process_Final$NOTE <- NULL
NBS_Process_Final$IND_WW_MG_NOTE <- NULL
NBS_Process_Final$IND_DW_MG_CONVERTED_NOTE <- NULL
NBS_Process_Final$IND_C_MG_CONVERTED_NOTE <- NULL
NBS_Process_Final$GROWTH_RATE_NOTE <- NULL


#Create wet weight biomass column converted individual wet weight and abundance

NBS_Process_Final <- mutate(NBS_Process_Final, BIOMASS_WW_MG_M3_MEAN = IND_WW_MG_MEASURED_MEAN*EST_NUM_PERM3)

NBS_Process_Final <- mutate(NBS_Process_Final, BIOMASS_WW_MG_M3_SD = IND_WW_MG_MEASURED_SD*EST_NUM_PERM3)


#Create dry weight biomass column converted individual dry weight and abundance

NBS_Process_Final <- mutate(NBS_Process_Final, BIOMASS_DW_MG_M3_MEAN = IND_DW_MG_CONVERTED_MEAN*EST_NUM_PERM3)

NBS_Process_Final <- mutate(NBS_Process_Final, BIOMASS_DW_MG_M3_SD = IND_DW_MG_CONVERTED_SD*EST_NUM_PERM3)


#Create carbon weight biomass column converted individual carbon weight and abundance

NBS_Process_Final <- mutate(NBS_Process_Final, BIOMASS_C_MG_M3_MEAN = IND_C_MG_CONVERTED_MEAN*EST_NUM_PERM3)

NBS_Process_Final <- mutate(NBS_Process_Final, BIOMASS_C_MG_M3_SD = IND_C_MG_CONVERTED_SD*EST_NUM_PERM3)


#Create carbon weight biomass column converted individual carbon weight and abundance

NBS_Process_Final <- mutate(NBS_Process_Final, PRODUCTION_MG_C_D_MEAN = (IND_C_MG_CONVERTED_MEAN*EST_NUM_PERM3*GROWTH_RATE_MEAN)*24)

NBS_Process_Final <- mutate(NBS_Process_Final, PRODUCTION_MG_C_D_SD = (IND_C_MG_CONVERTED_SD*EST_NUM_PERM3*GROWTH_RATE_SD)*24)





```


